### PR TITLE
I have tried to write the best possible code I could

### PR DESCRIPTION
**Pull request by PabloCorbCon**
This pull request is about #3.
I tried to **make my best upgrading the code**, let me know what you think about it.
Some things I have changed:
* on_ready() event
* documentation and comments in the bot.py file
* separation of the `get_bleach()`function in the `tools/` directory
* Simplification of statements.
Hope you like it.

### CODE REVIEW

**Review by sonuishaq67 — CHANGES_REQUESTED** [review]
I think line 20 gives an error while trying to run 
```
Traceback (most recent call last):
  File "/home/toor/temp/new/42ipdiscordbot/bot.py", line 20, in <module>
    client().event
TypeError: 'Client' object is not callable
```

after changing client().event to @client.event

/cringe doesnt work 
```
  File "/home/toor/temp/new/42ipdiscordbot/tools/bleach.py", line 9, in get_bleach
    with open(r) as file:
FileNotFoundError: [Errno 2] No such file or directory: '../bleach.txt'
```
this is the error

**Comment by sonuishaq67** [comment]
Theres another small error in the /tf function

**Comment by PabloCorbCon** [comment]
Ok so there is an error in the `/cringe` command and in the `/tf` command?

**Comment by sonuishaq67** [comment]
yupppp
```
  File "/home/toor/temp/new/42ipdiscordbot/tools/bleach.py", line 9, in get_bleach
    with open(r) as file:
FileNotFoundError: [Errno 2] No such file or directory: '../bleach.txt'
```

**Comment by PabloCorbCon** [comment]
Ok, lemme try to solve it.

**Comment by sonuishaq67** [comment]
Thanks for the contribution @PabloCorbCon 
I liked it very much :+1:

**Pull request merged**
