### PR TITLE
replaced requests.get with aysnchronous alternative

### PR DESCRIPTION
**Pull request by LakshyaShastri**
I replaced `requests.get` in the `bot.py` with one of its asynchronous alternatives. This was an essential change since requests.get is blocking and discord.py is an asynchronous library

### CODE REVIEW

**Comment by sonuishaq67** [comment]
Thanks for the contribution @LakshyaShastri 
I'll check and merge in a while

**Comment by LakshyaShastri** [comment]
No problem!

**Review by sonuishaq67 — CHANGES_REQUESTED** [review]
Theres a small error in r! meme 
response is not json as you already converted it with the function 
so if you rename response with the name meme and remove line 133 it might work

**Comment by LakshyaShastri** [comment]
Yes, you are correct! I didn't notice that you're using `.json()` on the response already 😅

**Review by sonuishaq67 — COMMENTED** [review]
yup it works

**Comment by sonuishaq67** [comment]
Ill be merging this 
thanks for the contribution!

**Pull request merged**
